<?php
$submissionObj = new backend();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCQ Editor - Add Submission</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/add_submission.css">
</head>

<body>
    <div class="main-container">
        <!-- Header Section -->
        <div class="header-section">
            <div class="header-title">
                <i class="fas fa-file-alt header-icon"></i>
                <h1 class="title-text">MCQ Editor - Add Submission</h1>
            </div>
            <p class="subtitle-text">Create and submit multiple choice questions for the portal</p>
        </div>

        <form action="pages/components/submission_manage.php" method="POST">

            <!-- Submission Details Section -->
            <div class="content-card">
                <div class="section-header">
                    <i class="fas fa-hashtag section-icon"></i>
                    <h2 class="section-title">Submission Details</h2>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-12">

                        <div class="input-group-wrapper">
                            <label for="submissionId" class="form-label">Submission ID</label>

                            <?php
                            $fetchSubmissions = $submissionObj->fetching("submissions", "*", null, null);

                            if (!empty($fetchSubmissions)) {
                                foreach ($fetchSubmissions as $submissions) {
                                    $fetched_set_id = $submissions['SystemID'];
                                    $ids = array_map(fn($s) => (int)str_replace("SET-", "", $s['SystemID']), $fetchSubmissions);
                                    $maxId = !empty($ids) ? max($ids) : 0;
                                }
                                $newID = $maxId + 1;
                                $formattedId = str_pad($newID, 5, "0", STR_PAD_LEFT);
                            ?>
                                <input type="text" class="form-control" name="setID" id="submissionId" value="SET-<?= $formattedId ?>" readonly>
                            <?php
                            } else {
                            ?>
                                <input type="text" class="form-control" name="setID" id="submissionId" value="SET-00001" readonly>
                            <?php
                            }
                            ?>
                            <p class="text-muted mt-1 ms-1" style="font-size:13px;">Unchanged ID (Generated by System)</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-12">
                        <div class="input-group-wrapper">
                            <label for="numMCQs" class="form-label">Number of MCQs to Upload *</label>
                            <input type="number" class="form-control" name="numMCQs" id="numMCQs" value="1" min="1" max="15">
                            <p class="text-muted mt-1 ms-1" style="font-size:13px;">Maximum limit to enter is 15</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Category Selection Section -->
            <div class="content-card">
                <div class="section-header">
                    <i class="fas fa-layer-group section-icon"></i>
                    <h2 class="section-title">Category Selection</h2>
                </div>

                <div class="row">
                    <div class="col-lg-4 col-md-12 col-12">
                        <div class="input-group-wrapper">
                            <label for="mainCategory" class="form-label">
                                Main Category
                                <span class="required-asterisk">*</span>
                            </label>
                            <div class="select-wrapper">
                                <select class="form-select" name="category_id" id="mainCategory" required>
                                    <option value="" selected>Select Main Category</option>
                                    <?php
                                    $fetchingCategories = $submissionObj->fetching("categories", "*", null, null);
                                    if (!empty($fetchingCategories)) {
                                        foreach ($fetchingCategories as $categories) {
                                            $category_id = $categories["id"];
                                            $category_name = $categories["category_name"];
                                    ?>
                                            <option value="<?= $category_id ?>"><?= $category_name ?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-12">
                        <div class="input-group-wrapper">
                            <label for="subcategory" class="form-label">
                                Subcategory
                                <span class="required-asterisk">*</span>
                            </label>
                            <div class="select-wrapper">
                                <select class="form-select" name="subcategory_id" id="subcategory" required>
                                    <option value="">Select Subcategory</option>
                                    <?php
                                    $fetchingSubCategories = $submissionObj->fetching("sub_categories", "*", null, null);
                                    if (!empty($fetchingSubCategories)) {
                                        foreach ($fetchingSubCategories as $subCategories) {
                                            $sub_category_id = $subCategories["id"];
                                            $sub_category_name = $subCategories["sub_category_name"];
                                    ?>
                                            <option value="<?= $sub_category_id ?>"><?= $sub_category_name ?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-12">
                        <div class="input-group-wrapper">
                            <label for="topic" class="form-label">
                                Topic
                                <span class="required-asterisk">*</span>
                            </label>
                            <div class="select-wrapper">
                                <select class="form-select" name="topic_id" id="topic" required>
                                    <option value="">Select Topic</option>
                                    <?php
                                    $fetchingtopics = $submissionObj->fetching("topics", "*", null, null);
                                    if (!empty($fetchingtopics)) {
                                        foreach ($fetchingtopics as $topics) {
                                            $topic_id = $topics["id"];
                                            $topic_name = $topics["topic_name"];
                                    ?>
                                            <option value="<?= $topic_id ?>"><?= $topic_name ?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <input type="submit" name="submit-form" class="btn btn-sm bg-success fw-bold text-white" value="Proceed Next">
            <!-- <a href="pages/add_mcqs.php" class="btn btn-sm bg-success fw-bold text-white">Proceed Next</a> -->

        </form>

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js"></script>

</body>

</html>