<?php
include("../../includes/connection.php");
$submissionObj = new backend();

// Handle AJAX request for subcategories
if (isset($_POST['action']) && $_POST['action'] == 'get_subcategories') {
    header('Content-Type: application/json');
    header('Cache-Control: no-cache, must-revalidate');
    
    if (isset($_POST['category_id']) && !empty($_POST['category_id'])) {
        $category_id = (int)$_POST['category_id'];
        
        try {
            $fetchingSubCategories = $submissionObj->fetching(
                "sub_categories", 
                "*", 
                null, 
                "category_id = " . $category_id
            );
            
            $subcategories = [];
            
            if (!empty($fetchingSubCategories) && is_array($fetchingSubCategories)) {
                foreach ($fetchingSubCategories as $sub_category) {
                    $subcategories[] = [
                        'id' => (int)$sub_category['id'],
                        'sub_category_name' => $sub_category['sub_category_name']
                    ];
                }
            }
            
            echo json_encode($subcategories);
            exit;
            
        } catch (Exception $e) {
            echo json_encode(['error' => 'Database error: ' . $e->getMessage()]);
            exit;
        }
    } else {
        echo json_encode(['error' => 'Category ID not provided']);
        exit;
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCQ Editor - Add Submission</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/add_submission.css">
</head>

<body>
    <div class="main-container">
        <!-- Header Section -->
        <div class="header-section">
            <div class="header-title">
                <i class="fas fa-file-alt header-icon"></i>
                <h1 class="title-text">MCQ Editor - Add Submission</h1>
            </div>
            <p class="subtitle-text">Create and submit multiple choice questions for the portal</p>
        </div>

        <!-- Hidden Input Fields for storing selected IDs -->
        <input type="text" id="selectedCategoryId" name="category_id" value="">
        <input type="text" id="selectedSubcategoryId" name="subcategory_id" value="">

        <!-- Submission Details Section -->
        <div class="content-card">
            <div class="section-header">
                <i class="fas fa-hashtag section-icon"></i>
                <h2 class="section-title">Submission Details</h2>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="input-group-wrapper">
                        <label for="submissionId" class="form-label">Submission ID</label>

                        <?php
                        $fetchSubmissions = $submissionObj->fetching("submissions", "*", null, null);

                        if (!empty($fetchSubmissions)) {
                            foreach ($fetchSubmissions as $submissions) {
                                $fetched_set_id = $submissions['SystemID'];
                                $ids = array_map(fn($s) => (int)str_replace("SET-", "", $s['SystemID']), $fetchSubmissions);
                                $maxId = !empty($ids) ? max($ids) : 0;
                            }
                            $newID = $maxId + 1;
                            $formattedId = str_pad($newID, 5, "0", STR_PAD_LEFT);
                        ?>
                            <input type="text" class="form-control" id="submissionId" value="SET-<?= $formattedId ?>" disabled readonly>
                        <?php
                        } else {
                        ?>
                            <input type="text" class="form-control" id="submissionId" value="SET-00001" readonly>
                        <?php
                        }
                        ?>
                        <p class="text-muted mt-1 ms-1" style="font-size:13px;">Unchanged ID (Generated by System)</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="input-group-wrapper">
                        <label for="numMCQs" class="form-label">Number of MCQs to Upload *</label>
                        <input type="number" class="form-control" id="numMCQs" value="1" min="1" max="15">
                        <p class="text-muted mt-1 ms-1" style="font-size:13px;">Maximum limit to enter is 15</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Category Selection Section -->
        <div class="content-card">
            <div class="section-header">
                <i class="fas fa-layer-group section-icon"></i>
                <h2 class="section-title">Category Selection</h2>
            </div>

            <div class="row">

                <div class="col-lg-6 col-md-12 col-12">
                    <div class="input-group-wrapper">
                        <label for="mainCategory" class="form-label">
                            Main Category
                            <span class="required-asterisk">*</span>
                        </label>
                        <div class="select-wrapper">
                            <select class="form-select" id="mainCategory" required onchange="loadSubcategories(this.value)">
                                <option value="" selected>Select Main Category</option>
                                <?php
                                $fetchingCategories = $submissionObj->fetching("categories", "*", null, null);
                                if (!empty($fetchingCategories)) {
                                    foreach ($fetchingCategories as $categories) {
                                        $category_id = (int)$categories["id"];
                                        $category_name = $categories["category_name"];
                                ?>
                                        <option value="<?= $category_id ?>"><?= $category_name ?></option>
                                <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-12 col-12">
                    <div class="input-group-wrapper">
                        <label for="subcategory" class="form-label">
                            Subcategory
                            <span class="required-asterisk">*</span>
                        </label>
                        <div class="select-wrapper">
                            <select class="form-select" id="subcategory" required onchange="updateSubcategoryId(this.value)">
                                <option value="">Select Subcategory</option>
                            </select>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
        
        <a href="pages/add_mcqs.php" class="btn btn-sm bg-success fw-bold text-white">Proceed Next</a>
    </div>

    <script>
    function loadSubcategories(categoryId) {
        console.log('Loading subcategories for category ID:', categoryId);
        
        // Update hidden field with category ID as integer
        document.getElementById('selectedCategoryId').value = parseInt(categoryId) || '';
        
        // Get subcategory dropdown
        const subcategorySelect = document.getElementById('subcategory');
        
        // Clear hidden subcategory ID
        document.getElementById('selectedSubcategoryId').value = '';
        
        if (categoryId && categoryId !== '') {
            // Set loading state
            subcategorySelect.innerHTML = '<option value="">Loading subcategories...</option>';
            
            // Load subcategories
            loadSubcategoriesData(categoryId);
        } else {
            // Reset dropdown
            subcategorySelect.innerHTML = '<option value="">Select Subcategory</option>';
        }
    }

    function loadSubcategoriesData(categoryId) {
        const subcategorySelect = document.getElementById('subcategory');
        
        const xhr = new XMLHttpRequest();
        xhr.open('POST', window.location.href, true);
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        
        xhr.onreadystatechange = function() {
            if (xhr.readyState === 4) {
                if (xhr.status === 200) {
                    try {
                        console.log('Subcategories raw response:', xhr.responseText);
                        const data = JSON.parse(xhr.responseText);
                        console.log('Subcategories parsed data:', data);
                        
                        subcategorySelect.innerHTML = '<option value="">Select Subcategory</option>';
                        
                        if (data.error) {
                            console.error('Subcategories Error:', data.error);
                            subcategorySelect.innerHTML = '<option value="">Error: ' + data.error + '</option>';
                        } else if (Array.isArray(data)) {
                            if (data.length > 0) {
                                data.forEach(function(subcat) {
                                    const option = document.createElement('option');
                                    option.value = subcat.id;
                                    option.textContent = subcat.sub_category_name;
                                    subcategorySelect.appendChild(option);
                                });
                            } else {
                                subcategorySelect.innerHTML = '<option value="">No subcategories found</option>';
                            }
                        } else {
                            subcategorySelect.innerHTML = '<option value="">Invalid response format</option>';
                        }
                    } catch (e) {
                        console.error('Subcategories JSON Parse Error:', e);
                        console.error('Raw response:', xhr.responseText);
                        subcategorySelect.innerHTML = '<option value="">Invalid JSON response</option>';
                    }
                } else {
                    console.error('Subcategories HTTP Error:', xhr.status);
                    subcategorySelect.innerHTML = '<option value="">HTTP Error: ' + xhr.status + '</option>';
                }
            }
        };
        
        xhr.send('action=get_subcategories&category_id=' + encodeURIComponent(categoryId));
    }

    function updateSubcategoryId(subcategoryId) {
        document.getElementById('selectedSubcategoryId').value = parseInt(subcategoryId) || '';
        console.log('Updated subcategory ID:', subcategoryId);
    }
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js"></script>
</body>

</html>